stages:
  - custom_dast

owasp_zap:
  image: python:3.12-slim
  stage: custom_dast
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apt-get update && apt-get install -y curl wget default-jre jq apt-transport-https ca-certificates gnupg
    - install -m 0755 -d /etc/apt/keyrings
    - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    - chmod a+r /etc/apt/keyrings/docker.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    - apt-get update
    - apt-get install -y docker-ce-cli
    - pip install --upgrade pip
    - pip install --no-cache-dir zaproxy==0.4.0
    - pwd
    - mkdir -p ./zap && cd ./zap
    - wget -N https://github.com/zaproxy/zaproxy/releases/download/v2.16.1/ZAP_2.16.1_Linux.tar.gz
    - tar -zxvf ZAP_2.16.1_Linux.tar.gz
    - rm ZAP_2.16.1_Linux.tar.gz
    - cd ZAP_2.16.1/plugin
    - wget https://github.com/zaproxy/zap-extensions/releases/download/exportreport-v6/exportreport-alpha-6.zap
    - cd $CI_PROJECT_DIR
    - echo 'export PATH_ZAP_SH=./zap/ZAP_2.16.1/zap.sh' >> ~/.bashrc
    - echo 'export ZAP_PORT=8090' >> ~/.bashrc
    - echo "Running Target Application"
    - docker build -t test:${CI_COMMIT_SHA} .
    - docker run -d -p 5050:5050 --name vul_flask --restart on-failure test:${CI_COMMIT_SHA}
    - sleep 30
    - docker ps
    - docker logs vul_flask
    - curl -I http://docker:5050
    - ./zap/ZAP_2.16.1/zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.addrs.addr.name=".*" -config api.addrs.addr.regex=true -config api.disablekey=true > /dev/null &
    - sleep 60
  script:
    - cd ./tests/
    - export TARGET_URL="http://docker:5050"
    - export ZAP_PORT=8090
    - export ZAP_HOST=localhost
    - python3 e2e_zap.py
  artifacts:
    paths:
      - ./tests/zap-report.json
    expire_in: 1 week
